config/routes.rb
Rails.application.routes.draw do
  root                    'sessions#new'
  get 'guide'         =>  'static#guide'
  get 'listes'        =>  'static#listes'
  post 'listes'       =>  'static#listes_create'
  get 'signup'        =>  'users#new'
  post 'login' 		    =>  'sessions#create'
  delete 'logout'     =>  'sessions#destroy'
  resources :users
  post 'add'		      =>	'usagers#create'
  get 'pqi'			      =>	'usagers#pqi'
  post 'usagers_vus'  =>  'usagers#post_vus'
  resources :usagers
  get 'stats'         =>  'stats#show'
  post 'stats'        =>  'stats#create'
  resources :maraudes, only: [:index, :show, :destroy, :new, :create]
  resources :rencontres, only: [:edit, :update, :destroy]
  resources :groupes
  resources :structures

  get	'pqi/:ville',
  	:controller => 'usagers',
  	:action 	  => 'pqi',
		:as 		    => :choix_ville

  get 'rencontres/:id',
    :controller => 'rencontres',
    :action     => 'new',
    :as         => :id_rencontre

  post 'rencontres/:id',
    :controller => 'rencontres',
    :action     => 'create',
    :as         => :id_rencontre_create

  get 'rencontres/edit/:id',
    :controller => 'rencontres',
    :action     => 'edit_form',
    :as         => :id_rencontre_edit

  post 'rencontres/edit/:id',
    :controller => 'rencontres',
    :action     => 'post_form',
    :as         => :id_rencontre_post

  get 'rencontres/groupe/:id',
    :controller => 'rencontres',
    :action     => 'new_groupe',
    :as         => :id_groupe

  post 'rencontres/groupe/:id',
    :controller => 'rencontres',
    :action     => 'post_groupe',
    :as         => :id_post_groupe

  get 'maraude-villes/:id',
    :controller => 'maraudes',
    :action     => 'villes',
    :as         => :id_m_villes

  post 'maraude-villes/:id',
    :controller => 'maraudes',
    :action     => 'post_villes',
    :as         => :id_post_villes

  get 'fiche/:id',
    :controller => 'usagers',
    :action     => 'fiche',
    :as         => :id_fiche

  get 'fiche_jour/:id',
    :controller => 'usagers',
    :action     => 'fiche_jour',
    :as         => :id_fiche_jour

  get 'edit_comp/:id',
    :controller => 'usagers',
    :action     => 'edit_comp',
    :as         => :id_edit_comp

  post 'edit_comp/:id',
    :controller => 'usagers',
    :action     => 'post_comp',
    :as         => :id_post_comp

  get 'stats/:date_deb/:date_fin',
    :controller => 'stats',
    :action     => 'show',
    :as         => :stats_dates

  get 'stats/:date_deb/:date_fin/ville/:ville',
    :controller => 'stats',
    :action     => 'show',
    :as         => :stats_dates_ville

  get 'stats/:date_deb/:date_fin/type/:type',
    :controller => 'stats',
    :action     => 'show',
    :as         => :stats_dates_type

  get 'stats/:date_deb/:date_fin/:type/:ville',
    :controller => 'stats',
    :action     => 'show',
    :as         => :stats_dates_type_ville

  get 'listes/:choix',
    :controller => 'static',
    :action     => 'listes',
    :as         => :listes_choix

  delete 'listes/Intervenants/:id',
    :controller => 'static',
    :action     => 'interv_destroy',
    :as         => :interv_destroy

  post 'listes/Intervenants',
    :controller => 'static',
    :action     => 'interv_create',
    :as         => :interv_create

  delete 'listes/Villes/:id',
    :controller => 'static',
    :action     => 'ville_destroy',
    :as         => :ville_destroy

  post 'listes/Villes',
    :controller => 'static',
    :action     => 'ville_create',
    :as         => :ville_create

  delete 'listes/Types/:id',
    :controller => 'static',
    :action     => 'type_destroy',
    :as         => :type_destroy

  post 'listes/Types',
    :controller => 'static',
    :action     => 'type_create',
    :as         => :type_create
end

app/models/maraude.rb
class Maraude < ActiveRecord::Base
  has_and_belongs_to_many :intervenants

  accepts_nested_attributes_for :intervenants, reject_if: lambda { |a| a[:nom].blank? },
                                               allow_destroy: true

  before_save :get_intervenants
  
  default_scope -> { order(date: :desc) }
  validates :date, 	presence: true,
  					        uniqueness: { scope: :type_maraude }
  validates :type_maraude, presence: true

  	def self.search(search)
      if search
        if Rails.env.production?
          where("to_char(maraudes.date, 'DD/MM/YY') ILIKE ? OR maraudes.type_maraude ILIKE? OR maraudes.villes ILIKE?", "%#{search}%", "%#{search}%", "%#{search}%") 
        else
          joins(intervenants: :maraudes).includes(intervenants: :maraudes).where("intervenants.nom LIKE ? OR maraudes.date LIKE ? OR maraudes.type_maraude LIKE? OR maraudes.villes LIKE?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
        end
      else
        scoped
      end
    end

  private
    def get_intervenants
      self.intervenants = self.intervenants.collect do |interv|
        Intervenant.find_or_create_by(nom: interv.nom.split(' ').map(&:capitalize).join(' ').split('-').map(&:capitalize).join('-'))
      end
    end
end

app/controllers/maraudes_controller.rb
class MaraudesController < ApplicationController
  before_action :logged_in_user,  only: [:new, :create, :index, :show, :villes, :post_villes, :destroy]
  before_action :admin_user,      only: :destroy
  before_action :benev_user,      only: [:new, :create, :villes, :post_villes, :destroy]

  def index
    delete_groupe
    if params[:search]
      @maraudes = Maraude.search(params[:search]).paginate(page: params[:page], per_page: 5)
      if @maraudes.empty?
        @maraudes = Maraude.search(params[:search].split('/').reverse.join('-')).paginate(page: params[:page], per_page: 10)
      end
    else
      @maraudes = Maraude.paginate(page: params[:page], per_page: 5)
    end
  end

  def show
    delete_groupe
  	@maraude = Maraude.find(params[:id])
  end

  def new
    delete_groupe
    @maraude = Maraude.new
    @types = []
    TypeRenc.where(mar: true).each do |t|
      @types << ["#{t.nom}"]
    end
  end

  def create
    @maraude = Maraude.new(maraude_params)
    @maraude.villes = ""
    if Maraude.find_by(date: params[:maraude][:date].to_date.strftime("%F"), type_maraude: params[:maraude][:type_maraude])
      flash[:danger] = "Cette maraude existe déjà"
      redirect_to new_maraude_path
    elsif @maraude.save
      @maraude.date = params[:maraude][:date].to_date.strftime("%F")
      @maraude.save
      flash[:success] = "Maraude créée"
      redirect_to id_m_villes_path(id: @maraude.id)
    else  
      flash[:danger] = "Renseignez la date et le type de la maraude"
      redirect_to new_maraude_path
    end
  end

  def villes
    delete_groupe
    store_id
    @villes = []
    Ville.where(ville_93: true).order('nom ASC').each do |v|
      @villes << ["#{v.nom}"]
    end
    @maraude = Maraude.find(session[:stored_id])
    session.delete(:stored_id)
  end

  def post_villes
    store_id
    villes = params[:maraude][:villes].reject{ |a| a == '0' }.join("\n")
    @maraude = Maraude.find(session[:stored_id])
    if @maraude.update_attribute(:villes, villes)
      if params[:maraude][:intervenants_attributes]
        @maraude.update_attribute(:intervenants_attributes, params[:maraude][:intervenants_attributes])
      end
      flash[:success] = "Modifications apportées"
      redirect_to @maraude
    else
      flash[:danger] = "Problème inconnu, veuillez réessayer"
      redirect_to id_m_villes_path(id: @maraude.id)
    end
    session.delete(:stored_id)
  end

  def destroy
    Maraude.find(params[:id]).destroy
    flash[:success] = "Maraude supprimée"
    redirect_to maraudes_path
  end

  private

    def maraude_params
      params.require(:maraude).permit(:date,
                                      :type_maraude,
                                      :villes,
                                      intervenants_attributes: [:nom,
                                                                :ref,
                                                                :_destroy])
    end
end

app/helpers/maraudes_helper.rb
module MaraudesHelper
end

app/views/maraudes/_form.html.erb
<%= simple_form_for(@maraude) do |f| %>

<div class="form-horizontal">
	<div class="part part-hover">
		<div class="form-group">
		  <%= f.label :date, class: "control-label col-md-3 col-sm-3 col-xs-3" %>
		  <div class="col-md-9 col-sm-9 col-xs-9 input-group date" id="datepicker">
			  <%= f.text_field :date, class: 'form-control', data: { date_format: 'DD/MM/YYYY', locale: 'fr' } %>
			  <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
			</div>
		</div>
		<div class="form-group">
	    <%= f.label :type_maraude, "Type de maraude", class: "control-label col-md-3 col-sm-3 col-xs-3" %>
	    <div class="col-md-9 col-sm-9 col-xs-9">
	      <%= f.select :type_maraude, @types, prompt: "Choisissez un type de maraude", class: 'form-control' %>
	    </div>
	  </div>

		<div class="form-group text-center">
			<%= f.submit "Créer la maraude", class: "btn btn-primary" %>
		</div>
	</div>
</div>

<% end %>

app/views/maraudes/_intervenant_fields.html.erb
<div class="nested-fields">
  <div class="form-inline">
  	<% if Rails.env.production? %>
    	<%= f.text_field :nom, data: {autocomplete_source: Intervenant.where.not("nom ILIKE ?", "%/%").order(:nom).map(&:nom)}, class: 'form-control intervenant-nom' %>
    <% else %>
    	<%= f.text_field :nom, data: {autocomplete_source: Intervenant.where.not("nom LIKE ?", "%/%").order(:nom).map(&:nom)}, class: 'form-control intervenant-nom' %>
    <% end %>
    <%= link_to_remove_association "Retirer", f, class: 'btn btn-danger' %>
  </div>
  <hr>
</div>

app/views/maraudes/_maraude.html.erb
<% # Listes villes parcourues et usagers rencontrés %>
<% rencontres = Rencontre.where(date: maraude.date, type_renc: maraude.type_maraude, prev: false, dnv: false, tel: false) %>
<% m_renc = [] %>
<% rencontres.each do |r| %>
  <% u = Usager.find_by(id: r.usager_id) %>
  <% m_renc << "#{r.ville} @#{u.sexe} #{u.nom} #{u.prenom}" %>
  <% if u.enfants.any? %>
    <% m_renc.last << " et #{pluralize(r.nb_enf, "enfant")}" %>
  <% end %>
<% end %>
<% arr = m_renc.sort %>
<% liste_villes_ok = [] %>
<% liste_usagers = [] %>
<% (0..(arr.length-1)).each do |i| %>
  <% ville = arr[i].split(' @').first %>
  <% usager = arr[i].split(' @').last %>
  <% if liste_villes_ok.last == "#{ville}" %>
    <% liste_usagers.last << "   - #{usager}\n" %>
  <% else %>
    <% liste_villes_ok << "#{ville}" %>
    <% liste_usagers << "   - #{usager}\n" %>
  <% end %>
<% end %>
<% disp_renc = "" %>
<% (0..(liste_villes_ok.length-1)).each do |n| %>
  <% disp_renc << "#{liste_villes_ok[n].upcase} :\n#{liste_usagers[n]}\n" %>
<% end %>


<% # Listes des dnv %>
<% dnv = Rencontre.where(date: maraude.date, type_renc: maraude.type_maraude, prev: false, dnv: true) %>
<% m_dnv = [] %>
<% dnv.each do |r| %>
  <% u = Usager.find_by(id: r.usager_id) %>
  <% m_dnv << "#{r.ville} @#{u.sexe} #{u.nom} #{u.prenom}" %>
<% end %>
<% arr = m_dnv.sort %>
<% liste_villes_dnv = [] %>
<% liste_usagers = [] %>
<% (0..(arr.length-1)).each do |i| %>
  <% ville = arr[i].split(' @').first %>
  <% usager = arr[i].split(' @').last %>
  <% if liste_villes_dnv.last == "#{ville}" %>
    <% liste_usagers.last << "   - #{usager}\n" %>
  <% else %>
    <% liste_villes_dnv << "#{ville}" %>
    <% liste_usagers << "   - #{usager}\n" %>
  <% end %>
<% end %>


<% # Liste des déroutages %>
<% der = "" %>
<% (0..(liste_villes_ok.length-1)).each do |i| %>
  <% if !maraude.villes.include?("#{liste_villes_ok[i]}") %>
    <% der << "#{liste_villes_ok[i]}\n" %>
  <% end %>
<% end %>
<% (0..(liste_villes_dnv.length-1)).each do |i| %>
  <% if !maraude.villes.include?("#{liste_villes_dnv[i]}") %>
    <% der << "#{liste_villes_dnv[i]}\n" unless der.include?("#{liste_villes_dnv[i]}") %>
  <% end %>
<% end %>
<% der = der.split("\n").sort.join("\n") %>


<% # Liste des signalements %>
<% sigs = Rencontre.where(date: maraude.date, type_renc: maraude.type_maraude, signale: true) %>
<% m_sig = [] %>
<% sigs.each do |r| %>
  <% u = Usager.find_by(id: r.usager_id) %>
  <% m_sig << "#{r.ville} @#{u.sexe} #{u.nom} #{u.prenom}" %>
  <% if u.enfants.any? %>
    <% m_sig.last << " et #{pluralize(r.nb_enf, "enfant")}" %>
  <% end %>
<% end %>
<% arr = m_sig.sort %>
<% liste_villes = [] %>
<% liste_usagers = [] %>
<% (0..(arr.length-1)).each do |i| %>
  <% ville = arr[i].split(' @').first %>
  <% usager = arr[i].split(' @').last %>
  <% if liste_villes.last == "#{ville}" %>
    <% liste_usagers.last << "   - #{usager}\n" %>
  <% else %>
    <% liste_villes << "#{ville}" %>
    <% liste_usagers << "   - #{usager}\n" %>
  <% end %>
<% end %>
<% disp_sig = "" %>
<% (0..(liste_villes.length-1)).each do |n| %>
  <% disp_sig << "#{liste_villes[n].upcase} :\n#{liste_usagers[n]}\n" %>
<% end %>


<% # Liste des accompagnements %>
<% accomps = Rencontre.where(date: maraude.date, type_renc: maraude.type_maraude, accomp: true) %>
<% m_accomp = [] %>
<% accomps.each do |r| %>
  <% u = Usager.find_by(id: r.usager_id) %>
  <% m_accomp << "#{r.ville} @#{u.sexe} #{u.nom} #{u.prenom}" %>
  <% if u.enfants.any? %>
    <% m_accomp.last << " et #{pluralize(r.nb_enf, "enfant")}" %>
  <% end %>
<% end %>
<% arr = m_accomp.sort %>
<% liste_villes = [] %>
<% liste_usagers = [] %>
<% (0..(arr.length-1)).each do |i| %>
  <% ville = arr[i].split(' @').first %>
  <% usager = arr[i].split(' @').last %>
  <% if liste_villes.last == "#{ville}" %>
    <% liste_usagers.last << "   - #{usager}\n" %>
  <% else %>
    <% liste_villes << "#{ville}" %>
    <% liste_usagers << "   - #{usager}\n" %>
  <% end %>
<% end %>
<% disp_accomp = "" %>
<% (0..(liste_villes.length-1)).each do |n| %>
  <% disp_accomp << "#{liste_villes[n].upcase} :\n#{liste_usagers[n]}\n" %>
<% end %>


<tr id="maraude">
  <td>
    <%= link_to "#{maraude.type_maraude}", maraude, class: "lead" %><br>
    <%= link_to "#{maraude.date.strftime("%d/%m/%y")}", maraude, class: "lead" %><br>
    <% if maraude.intervenants.any? %>
      <% maraude.intervenants.each do |int| %>
        <%= "/ #{int.nom} /" %>
      <% end %>
    <% end %>

    <% villes = maraude.villes.split("\n") %>
    <% (0..(villes.length-1)).each do |i| %>
      <% if liste_villes_ok.include?("#{villes[i]}") || liste_villes_dnv.include?("#{villes[i]}") %>
        <% villes[i] << " ☑" %>
      <% else %>
        <% villes[i] << " ☐" %>
      <% end %>
    <% end %>
    <pre class="maraude-list"><%= villes.join("\n") %></pre>

    <% if !der.empty? && !maraude.villes.empty? %>
      Déroutage(s) : <pre class="maraude-list"><%= der %></pre>
    <% end %>

    <%= link_to "Modifier villes et intervenants", id_m_villes_path(:id => maraude.id) unless current_user.benev? %>
  </td>
  <td>
    <pre class="maraude-list text-justify"><%= disp_renc %></pre>
  </td>
  <td>
    <% if disp_sig.present? %>
      <p class="lead">Signalements</p>
      <pre class="maraude-list text-justify"><%= disp_sig %></pre>
    <% end %>

    <% if disp_accomp.present? %>
      <p class="lead">Accompagnements</p>
      <pre class="maraude-list text-justify"><%= disp_accomp %></pre>
    <% end %>
  </td>
</tr>

app/views/maraudes/_table_h.html.erb
<th>Maraude</th>
<th>Rencontres</th>
<th>Signalements et accompagnements</th>

app/views/maraudes/index.html.erb
<% provide(:title, 'Maraudes') %>

<h1>
  Index des maraudes
  <% unless current_user.benev? %>
    <br><%= link_to "Nouvelle maraude", new_maraude_path, class: "btn btn-info" %>
  <% end %>
</h1>

<%= will_paginate %>

<%= form_tag(maraudes_path, :method => "get", id: "search-form", role: 'search', class: "navbar navbar-search") do %>
  <div class="form-group col-md-4 col-sm-4 col-xs-4">
    <%= text_field_tag :search, params[:search], placeholder: "Rechercher des maraudes", class: 'form-control' %>
  </div>
  <%= submit_tag "Rechercher", class: 'btn btn-default' %>
<% end %>

<h4 class="text-right"><%= pluralize(@maraudes.count, "maraude") %></h4>

<% if !@maraudes.empty? %>
  <table class="maraudes table table-responsive table-hover">
    <tr id="table_head">
      <%= render 'table_h' %>
    </tr>
    <%= render @maraudes %>
  </table>
<% else %>
	<p class="lead text-center">Aucune maraude correspondant au(x) terme(s) : "<%= params[:search] %>".</p>
<% end %>

<%= will_paginate %>

app/views/maraudes/new.html.erb
<% provide(:title, "Nouvelle maraude") %>

<h1>Nouvelle maraude</h1>

<h4>On renseignera la date et le type de la maraude.</h4>

<div class="row">
  <div class="col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-6 col-xs-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/maraudes/villes.html.erb
<% provide(:title, "#{@maraude.type_maraude} du #{@maraude.date.strftime("%d/%m/%y")}") %>

<h1><%= @maraude.type_maraude %> du <%= @maraude.date.strftime("%d/%m/%y") %></h1>

<%= form_for(@maraude, url: id_post_villes_path(id: @maraude.id), method: :post) do |f| %>

<h3>Intervenants</h3>
  
  <ul id="intervenants">
     <%= f.fields_for :intervenants do |interv| %>
        <li><%= render 'intervenant_fields', f: interv %></li>
     <% end %>
     <%= link_to_add_association 'Ajouter un intervenant', f, :intervenants, class: 'btn btn-info links' %>
  </ul>

<hr>

<h3>Villes théoriquement parcourues</h3>

  <div class="row">
    <div class="col-md-4 col-sm-4 col-xs-4">
      <% for ville in @villes[0..((@villes.length/3).floor)] do %>
        <% if @maraude.villes.split("\n").include?("#{ville.first}") %>
          <%= f.check_box :villes, { :multiple => true, :checked => true }, "#{ville.first}" %>
          <%= ville.first %><br>
        <% else %>
          <%= f.check_box :villes, { :multiple => true, :checked => false }, "#{ville.first}" %>
          <%= ville.first %><br>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-4 col-sm-4 col-xs-4">
      <% for ville in @villes[((@villes.length/3).floor + 1)..(((@villes.length/3)*2).floor + 1)] do %>
        <% if @maraude.villes.split("\n").include?("#{ville.first}") %>
          <%= f.check_box :villes, { :multiple => true, :checked => true }, "#{ville.first}" %>
          <%= ville.first %><br>
        <% else %>
          <%= f.check_box :villes, { :multiple => true, :checked => false }, "#{ville.first}" %>
          <%= ville.first %><br>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-4 col-sm-4 col-xs-4">
      <% for ville in @villes[(((@villes.length/3).floor)*2 + 2)..(@villes.length - 1)] do %>
        <% if @maraude.villes.split("\n").include?("#{ville.first}") %>
          <%= f.check_box :villes, { :multiple => true, :checked => true }, "#{ville.first}" %>
          <%= ville.first %><br>
        <% else %>
          <%= f.check_box :villes, { :multiple => true, :checked => false }, "#{ville.first}" %>
          <%= ville.first %><br>
        <% end %>
      <% end %>
    </div>
  </div>

  <br>

  <div class="text-center">
    <%= f.submit "Valider", class: "btn btn-primary" %>
  </div>
<% end %>