config/routes.rb
Rails.application.routes.draw do
  root                    'sessions#new'
  get 'guide'         =>  'static#guide'
  get 'listes'        =>  'static#listes'
  post 'listes'       =>  'static#listes_create'
  get 'signup'        =>  'users#new'
  post 'login' 		    =>  'sessions#create'
  delete 'logout'     =>  'sessions#destroy'
  resources :users
  post 'add'		      =>	'usagers#create'
  get 'pqi'			      =>	'usagers#pqi'
  post 'usagers_vus'  =>  'usagers#post_vus'
  resources :usagers
  get 'stats'         =>  'stats#show'
  post 'stats'        =>  'stats#create'
  resources :maraudes, only: [:index, :show, :destroy, :new, :create]
  resources :rencontres, only: [:edit, :update, :destroy]
  resources :groupes
  resources :structures

  get	'pqi/:ville',
  	:controller => 'usagers',
  	:action 	  => 'pqi',
		:as 		    => :choix_ville

  get 'rencontres/:id',
    :controller => 'rencontres',
    :action     => 'new',
    :as         => :id_rencontre

  post 'rencontres/:id',
    :controller => 'rencontres',
    :action     => 'create',
    :as         => :id_rencontre_create

  get 'rencontres/edit/:id',
    :controller => 'rencontres',
    :action     => 'edit_form',
    :as         => :id_rencontre_edit

  post 'rencontres/edit/:id',
    :controller => 'rencontres',
    :action     => 'post_form',
    :as         => :id_rencontre_post

  get 'rencontres/groupe/:id',
    :controller => 'rencontres',
    :action     => 'new_groupe',
    :as         => :id_groupe

  post 'rencontres/groupe/:id',
    :controller => 'rencontres',
    :action     => 'post_groupe',
    :as         => :id_post_groupe

  get 'maraude-villes/:id',
    :controller => 'maraudes',
    :action     => 'villes',
    :as         => :id_m_villes

  post 'maraude-villes/:id',
    :controller => 'maraudes',
    :action     => 'post_villes',
    :as         => :id_post_villes

  get 'fiche/:id',
    :controller => 'usagers',
    :action     => 'fiche',
    :as         => :id_fiche

  get 'fiche_jour/:id',
    :controller => 'usagers',
    :action     => 'fiche_jour',
    :as         => :id_fiche_jour

  get 'edit_comp/:id',
    :controller => 'usagers',
    :action     => 'edit_comp',
    :as         => :id_edit_comp

  post 'edit_comp/:id',
    :controller => 'usagers',
    :action     => 'post_comp',
    :as         => :id_post_comp

  get 'stats/:date_deb/:date_fin',
    :controller => 'stats',
    :action     => 'show',
    :as         => :stats_dates

  get 'stats/:date_deb/:date_fin/ville/:ville',
    :controller => 'stats',
    :action     => 'show',
    :as         => :stats_dates_ville

  get 'stats/:date_deb/:date_fin/type/:type',
    :controller => 'stats',
    :action     => 'show',
    :as         => :stats_dates_type

  get 'stats/:date_deb/:date_fin/:type/:ville',
    :controller => 'stats',
    :action     => 'show',
    :as         => :stats_dates_type_ville

  get 'listes/:choix',
    :controller => 'static',
    :action     => 'listes',
    :as         => :listes_choix

  delete 'listes/Intervenants/:id',
    :controller => 'static',
    :action     => 'interv_destroy',
    :as         => :interv_destroy

  post 'listes/Intervenants',
    :controller => 'static',
    :action     => 'interv_create',
    :as         => :interv_create

  delete 'listes/Villes/:id',
    :controller => 'static',
    :action     => 'ville_destroy',
    :as         => :ville_destroy

  post 'listes/Villes',
    :controller => 'static',
    :action     => 'ville_create',
    :as         => :ville_create

  delete 'listes/Types/:id',
    :controller => 'static',
    :action     => 'type_destroy',
    :as         => :type_destroy

  post 'listes/Types',
    :controller => 'static',
    :action     => 'type_create',
    :as         => :type_create
end

app/models/usager.rb
class Usager < ActiveRecord::Base
  has_many :rencontres, :dependent => :destroy
  has_many :enfants, :dependent => :destroy
  belongs_to :groupe
  has_and_belongs_to_many :structures

  accepts_nested_attributes_for :enfants, reject_if: lambda { |a| a[:nom].blank? && a[:prenom].blank? },
                                          allow_destroy: true

  before_save { nom.upcase! }
  before_save { self.prenom = prenom.split(' ').map(&:capitalize).join(' ').split('-').map(&:capitalize).join('-') }

  default_scope -> { order(nom: :asc, prenom: :asc) }
  
  validate :at_least_one
  validates :user_id, presence: true
  validates :sexe, presence: true, allow_blank: true
  validates :ville, presence: true

  def groupe_nom
    groupe.try(:nom)
  end

  def groupe_nom=(nom)
    self.groupe = Groupe.find_or_create_by(nom: nom.split(' ').map(&:capitalize).join(' ').split('-').map(&:capitalize).join('-')) if nom.present?
  end

    def self.search(search)
      if search
        if Rails.env.production?
          where("usagers.nom ILIKE ? OR usagers.ville ILIKE? OR usagers.prenom ILIKE? OR usagers.adresse ILIKE? OR usagers.adresse_précis ILIKE? OR usagers.sexe ILIKE? OR to_char(usagers.date_naissance, 'DD/MM/YYYY') ILIKE? OR usagers.tel ILIKE?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
        else
          where("nom LIKE ? OR ville LIKE? OR prenom LIKE? OR adresse LIKE? OR adresse_précis LIKE? OR sexe LIKE? OR date_naissance LIKE? OR tel LIKE?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
        end
      else
        scoped
      end
    end

  private
  	def at_least_one
  	  if self.prenom.blank? && self.nom.blank?
  	    self.errors.add(:base, "Please fill at least the name or surname")
  	  end
    end
end

app/controllers/usagers_controller.rb
class UsagersController < ApplicationController
  before_action :logged_in_user,  only: [:new, :show, :index, :create, :edit, :update, :destroy, :pqi, :fiche, :fiche_jour, :edit_comp, :post_comp]
  before_action :admin_user,      only: :destroy
  before_action :benev_user,      only: [:edit, :update, :destroy, :fiche, :fiche_jour, :edit_comp, :post_comp]

  def new
    delete_groupe
    session[:stored] = "new"
    @usager = Usager.new
    @villes = [["Ville inconnue"], ["Autre (hors 93)"]]
    Ville.where(ville_93: true).order('nom ASC').each do |v|
      @villes << ["#{v.nom}"]
    end
    gon.noms = []
    gon.prenoms = []
    Usager.all.each do |u|
      gon.noms << "#{u.nom}"
      gon.prenoms << "#{u.prenom}"
    end
  end

  def index
    delete_groupe
    if params[:search]
      @usagers = Usager.search(params[:search]).paginate(page: params[:page], per_page: 50)
      if @usagers.empty?
        @usagers = Usager.search(params[:search].split('/').reverse.join('-')).paginate(page: params[:page], per_page: 50)
      end
    else
      @usagers = Usager.paginate(page: params[:page], per_page: 50)
    end
    @vus = Usager.where(vu: false).order('nom ASC')
  end

  def post_vus
    usagers_vus = params[:usagers][:vus].reject{ |a| a == '0' }
    usagers_vus.each do |v|
      Usager.find(v).update_attribute(:vu, true)
    end
    redirect_to usagers_path
  end

  def show
    delete_groupe
  	@usager = Usager.find(params[:id])
  end

  def create
    @usager = Usager.new(usager_params)
    @usager.user_id = current_user.id
    @usager.vu = false
    if params[:add_inconnu]
      if !params[:usager][:sexe]
        @usager.sexe = ""
      end
      @usager.nom = ""
      @usager.prenom = "Inconnu" if @usager.sexe == "Mr"
      @usager.prenom = "Inconnue" if @usager.sexe == "Mme"
      @usager.prenom = "Inconnu(e)" if @usager.sexe == ""
    end
    if @usager.save
      if @usager.ref.present?
        interv = Intervenant.find_or_create_by(nom: @usager.ref.split(' ').map(&:capitalize).join(' ').split('-').map(&:capitalize).join('-'))
        interv.ref = true
        interv.save
      end
      if @usager.pqi
        @usager.pqi_histo = ""
        @usager.pqi_histo << Date.today.strftime("%d/%m/%y")
        @usager.save
      end
      flash[:success] = "Nouvel usager ajouté !"
      unless current_user.benev?
        redirect_to id_edit_comp_path(id: @usager.id)
      else
        redirect_to id_rencontre_path(id: @usager.id)
      end
    else
      if params[:add_inconnu]
        flash[:danger] = "Renseignez la ville où se trouve l'usager inconnu."
        redirect_to new_usager_path
      else
        flash[:danger] = "Ajoutez au moins le nom ou le prénom de l'usager ! Si ils ne sont pas connus, spécifiez 'Inconnu' pour le nom. Il faut également renseigner son sexe et sa ville."
        redirect_to new_usager_path
      end
    end
  end

  def edit
    delete_groupe
    session[:stored] = "edit"
    @villes = [["Ville inconnue"], ["Autre (hors 93)"]]
    Ville.where(ville_93: true).order('nom ASC').each do |v|
      @villes << ["#{v.nom}"]
    end
  	@usager = Usager.find(params[:id])
  end

  def update
  	@usager = Usager.find(params[:id])
    stored_pqi = @usager.pqi
    if @usager.update_attribute(:pqi, params[:usager][:pqi]) && session[:stored] == "edit" && @usager.pqi != stored_pqi
      if @usager.update_attributes(usager_params)
        if @usager.pqi
          if @usager.pqi_histo
            @usager.pqi_histo << " ///// "
          else
            @usager.pqi_histo = ""
          end
        else
          @usager.pqi_histo << " - " unless @usager.pqi_histo.nil?
        end
        arr = @usager.pqi_histo.split(' ///// ')
        if arr.last == "#{Date.today.strftime("%d/%m/%y")} - "
          if arr.length >= 2
            @usager.pqi_histo = arr[0..(arr.length-2)].join(' ///// ')
          else
            @usager.pqi_histo = nil
          end
        else
          @usager.pqi_histo << Date.today.strftime("%d/%m/%y") unless @usager.pqi_histo.nil?
        end
        @usager.update_attributes(usager_params)
        if @usager.update_attribute(:ref, params[:usager][:ref])
          interv = Intervenant.find_or_create_by(nom: @usager.ref.split(' ').map(&:capitalize).join(' ').split('-').map(&:capitalize).join('-'))
          interv.ref = true
          interv.save
        end
        if params[:usager][:groupe_nom] == ""
          @usager.update_attribute(:groupe_id, nil)
        end
        prenoms = ["Inconnu", "Inconnue", "Inconnu(e)"]
        noms = ["INCONNU", "INCONNUE", "INCONNU(E)"]
        @usager.update_attributes(prenom: "Inconnu", nom: "") if @usager.sexe == "Mr" && (prenoms.include?(@usager.prenom) || noms.include?(@usager.nom))
        @usager.update_attributes(prenom: "Inconnue", nom: "") if @usager.sexe == "Mme" && (prenoms.include?(@usager.prenom) || noms.include?(@usager.nom))
        @usager.update_attributes(prenom: "Inconnu(e)", nom: "") if @usager.sexe == "" && (prenoms.include?(@usager.prenom) || noms.include?(@usager.nom))
        flash[:success] = "Usager édité"
        redirect_to @usager
      else
        flash[:danger] = "Mise à jour impossible. Veillez à remplir les informations nécessaires (Nom et/ou prénom, ville et sexe)."
        @usager.update_attribute(:pqi, stored_pqi)
        render 'edit'
      end
    elsif session[:stored] == "fiche"
      @usager.update_attribute(:fiche, params[:usager][:fiche])
      @usager.update_attribute(:pqi, stored_pqi)
      flash[:success] = "Fiche de rencontres usager éditée"
      redirect_to @usager
    elsif session[:stored] == "fiche_jour"
      @usager.update_attribute(:fiche_jour, params[:usager][:fiche_jour])
      @usager.update_attribute(:pqi, stored_pqi)
      flash[:success] = "Fiche de suivi jour usager éditée"
      redirect_to @usager
    elsif @usager.update_attributes(usager_params)
      if @usager.update_attribute(:ref, params[:usager][:ref])
        interv = Intervenant.find_or_create_by(nom: @usager.ref.split(' ').map(&:capitalize).join(' ').split('-').map(&:capitalize).join('-'))
        interv.ref = true
        interv.save
      end
      if params[:usager][:groupe_nom] == ""
        @usager.update_attribute(:groupe_id, nil)
      end
      prenoms = ["Inconnu", "Inconnue", "Inconnu(e)"]
      noms = ["INCONNU", "INCONNUE", "INCONNU(E)"]
      @usager.update_attributes(prenom: "Inconnu", nom: "") if @usager.sexe == "Mr" && (prenoms.include?(@usager.prenom) || noms.include?(@usager.nom))
      @usager.update_attributes(prenom: "Inconnue", nom: "") if @usager.sexe == "Mme" && (prenoms.include?(@usager.prenom) || noms.include?(@usager.nom))
      @usager.update_attributes(prenom: "Inconnu(e)", nom: "") if @usager.sexe == "" && (prenoms.include?(@usager.prenom) || noms.include?(@usager.nom))
      flash[:success] = "Usager édité"
      redirect_to @usager
    else
      flash[:danger] = "Mise à jour impossible. Veillez à remplir les informations nécessaires (Nom et/ou prénom, ville et sexe)."
      render 'edit'
    end
  end

  def destroy
  	Usager.find(params[:id]).destroy
  	flash[:success] = "Usager supprimé"
  	redirect_to usagers_url
  end

  def pqi
    delete_groupe
    store_ville
    @villes = []
    Ville.where(ville_93: true).order('nom ASC').each do |v|
      @villes << ["#{v.nom}"]
    end
    @usagers = Usager.where(pqi: true, ville: session[:stored_ville]).order('adresse ASC, adresse_précis ASC, nom ASC') unless session[:stored_ville] == "pqi"
    @ville_actuelle = session[:stored_ville]
    session.delete(:stored_ville)
  end

  def fiche
    delete_groupe
    store_last
    store_id
    @usager = Usager.find(session[:stored_id])
    session.delete(:stored_id)
  end

  def fiche_jour
    delete_groupe
    store_last
    store_id
    @usager = Usager.find(session[:stored_id])
    session.delete(:stored_id)
  end

  def edit_comp
    delete_groupe
    store_id
    session[:stored] = "edit_comp"
    @usager = Usager.find(session[:stored_id])
    @ressources = [ ["Salaire", "Salaire"],
                    ["Retraite", "Retraite"],
                    ["RSA", "RSA"],
                    ["AAH", "AAH"],
                    ["Prestation(s) familiale(s)", "Prestation(s) familiale(s)"],
                    ["ATA", "ATA"],
                    ["ASS", "ASS"],
                    ["ARE", "ARE"],
                    ["Rémunération de formation", "Rémunération de formation"],
                    ["Pension d'invalidité", "Pension d'invalidité"],
                    ["Autre", "Autre"],
                    ["Sans ressources", "Sans ressources"]]
    @prestas_med = [["CMU", "CMU"],
                    ["CMUC", "CMUC"],
                    ["AME", "AME"],
                	["Régime général", "Régime général"]]
    session.delete(:stored_id)
  end

  def post_comp
    store_id
    ressources = params[:usager][:ressources].reject{ |a| a == '0' }.join("\n")
    prestas_med = params[:usager][:prestas_med].reject{ |a| a == '0' }.join("\n")
    @usager = Usager.find(session[:stored_id])
    if @usager.update_attributes(ressources: ressources, prestas_med: prestas_med) && @usager.update_attributes(comp_params)
      flash[:success] = "Informations complémentaires éditées"
      if Usager.maximum("id") == @usager.id
        redirect_to id_rencontre_path(id: @usager.id)
      else
        redirect_to @usager
      end
    else
      flash[:danger] = "Problème inconnu, veuillez réessayer"
      redirect_to id_edit_comp_path(id: @usager.id)
    end
    session.delete(:stored_id)
  end

  private
    def usager_params
      params.require(:usager).permit( :nom,
                                      :prenom,
                                      :sexe,
                                      :ville,
                                      :adresse,
                                      :adresse_précis,
                                      :date_naissance,
                                      :tel,

app/helpers/usagers_helper.rb
module UsagersHelper
  def dates_5(dat)
    if dat
      if dat.length > 52
        d = dat.split(' - ')
        d[0..4].join(' - ') 
      else
        dat
      end
    end
  end
end

app/views/usagers/_table_h.html.erb
<th class="ville">Ville</th>
<th class="adresse">Adresse</th>
<th class="comp_adr">Complément d'adresse</th>
<th class="date_naissance">Date de naissance</th>
<th class="tel">Téléphone</th>
<th class="pqi">PQI ?</th>
<th class="infos">Informations d'ajout</th>

app/views/usagers/_table_h_soft.html.erb
<th class="identité">Identité</th>
<th class="adresse">Adresse</th>
<th class="pqi">PQI ?</th>
<th class="rencontres">Dernières rencontres</th>

app/views/usagers/_usager.html.erb
<tr id="usager"
<% if usager.pqi %>
  class="pqi"
<% else %>
  class="no-pqi"
<% end %>
>

  <td>
    <%= link_to "#{usager.sexe} #{usager.nom} #{usager.prenom}", usager %>
    <% if usager.enfants.any? %>
      <br><%= pluralize(usager.enfants.count, 'enfant') %>
    <% end %>
    <% if usager.date_naissance? %>
      <br><%= "#{usager.date_naissance.strftime("%d/%m/%Y")}" %>
    <% end %>
    <% if usager.tel? %>
      <br><%= "#{usager.tel}" %>
    <% end %>
    <% if usager.ref.present? %>
      <br><small>Référent : <%= usager.ref %></small>
    <% end %>
    <% if usager.groupe %>
      <br><%= link_to "#{usager.groupe.nom}", usager.groupe %>
    <% end %>
  </td>
  <td>
    <%= "#{usager.ville.upcase}" %>
    <% if usager.adresse %>
      <br><%= "#{usager.adresse}" %>
    <% end %>
    <% if usager.adresse_précis %>
      <br><%= "#{usager.adresse_précis}" %>
    <% end %>
  </td>
  <td>
    <% dates_renc = [] %>
    <% Rencontre.where(usager_id: usager.id, prev: false, dnv: false, tel: false).each do |r| %>
      <% dates_renc << "#{r.date.strftime("%d/%m/%y")}" %>
    <% end %>
    <%= dates_5(dates_renc.join(' - ')) %><br>

    <% if Rencontre.find_by(usager_id: usager.id, prev: true) %>
      <% n = Rencontre.where(usager_id: usager.id, prev: true).count %>
      <%= pluralize(n, "rencontre") %> <%= "prévue".pluralize(n) %><br>
    <% end %>

    <%= link_to "Ajouter une rencontre", id_rencontre_path(:id => usager.id), id: 'ajout-rencontre', "data-no-turbolink" => true %>

  </td>
  <% if current_user.admin? %>
    <td>
      <%= link_to "Modifier", edit_usager_path(usager) %><br>
      <%= link_to "Supprimer", usager,  method: :delete,
                                        data: { confirm: "Etes-vous sûr(e) ?" } %>
    </td>
  <% end %>
</tr>

app/views/usagers/edit_comp.html.erb
<% provide(:title, "Informations complémentaires") %>

<h1>Edition des informations complémentaires de <%= "#{@usager.sexe} #{@usager.nom} #{@usager.prenom}" %></h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-8 col-xs-offset-2">
    <%= render "edit_comp_form" %>
  </div>
</div>

app/views/usagers/index.html.erb
<% provide(:title, 'Usagers') %>
<h1>
  Usagers
  <br><%= link_to "Index des groupes", groupes_path, class: 'btn btn-info' %>
</h1>

<% if current_user.admin? && @vus.present? %>
  <div class="row">
    <div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1 usagers-vus">
      <h3 class="text-center">Nouveaux usagers</h3>
      <%= form_tag(usagers_vus_path, method: :post) do %>
        <% @vus.each do |usager| %>
          <div class="row usager-vu">
            <div class="col-md-4 col-sm-4 col-xs-4">
              <%= link_to "#{usager.sexe} #{usager.nom} #{usager.prenom}", usager %>
              <% if usager.enfants.any? %>
                <br><%= pluralize(usager.enfants.count, 'enfant') %>
              <% end %>
              <% if usager.date_naissance? %>
                <br><%= "#{usager.date_naissance.strftime("%d/%m/%Y")}" %>
              <% end %>
              <% if usager.tel? %>
                <br><%= "#{usager.tel}" %>
              <% end %>
              <% if usager.ref.present? %>
                <br><small>Référent : <%= usager.ref %></small>
              <% end %>
              <% if usager.groupe %>
                <br><%= link_to "#{usager.groupe.nom}", usager.groupe %>
              <% end %>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-4">
              <%= "#{usager.ville.upcase}" %>
              <% if usager.adresse %>
                <br><%= "#{usager.adresse}" %>
              <% end %>
              <% if usager.adresse_précis %>
                <br><%= "#{usager.adresse_précis}" %>
              <% end %>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-3">
              <% user = User.find(usager.user_id) %>
              <%= link_to "#{user.identifiant}", user %><%= " (#{usager.created_at.strftime("%d/%m/%Y, %H:%M")})" %>
            </div>
            <div class="col-md-1 col-sm-1 col-xs-1">
              <%= check_box_tag 'usagers[vus][]', "#{usager.id}" %>
            </div>
          </div>
        <% end %>
        <div class="text-center">
          <span class="lead">Les usagers cochés seront déclarés comme vus</span>
          <br><br><%= submit_tag "OK", class: 'btn btn-lg btn-info' %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<%= will_paginate %>

<%= form_tag(usagers_path, :method => "get", id: "search-form", role: 'search', class: "navbar navbar-search") do %>
  <div class="form-group col-md-4 col-sm-4 col-xs-4">
    <%= text_field_tag :search, params[:search], placeholder: "Rechercher des usagers", class: 'form-control' %>
  </div>
  <%= submit_tag "Rechercher", class: 'btn btn-default' %>
<% end %>

<h4>Au passage de la souris, en vert les usagers sur PQI, en rouge ceux qui n'y sont pas.</h4>

<h4 class="text-right"><%= pluralize(@usagers.count, "usager") %></h4>

<% if !@usagers.empty? %>
  <table class="usagers table table-responsive table-hover text-center">
    <tr id="table_head">
      <th>Identité</th>
      <th>Adresse</th>
      <th>Dernières rencontres</th>
      <% if current_user.admin? %>
        <th>Edition et Suppression (privilège admin)</th>
      <% end %>
    </tr>
    <%= render @usagers %>
  </table>
<% else %>
  <p class="lead text-center">Aucun usager correspondant au(x) terme(s) : "<%= params[:search] %>".</p>
<% end %>

<%= will_paginate %>

app/views/usagers/pqi.html.erb
<% provide(:title, 'PQI') %>

<div id="no-print">
  <h1>PQI <span class="label label-default"><%= Usager.where(pqi: true).count %></span></h1>

  <% renc_prev = Rencontre.where(prev: true) %>
  <% if renc_prev.any? %>
    <div id="accordion" class="renc-prev">
      <h3><%= pluralize(renc_prev.count, "Rencontre") %> <%= "prévue".pluralize(renc_prev.count) %></h3>

      <div>
        <ul>
          <% renc_prev.each do |r| %>
            <% u = Usager.find(r.usager_id) %>
            <li class="lead">
              <%= link_to "#{u.sexe} #{u.nom} #{u.prenom} (#{r.ville})", u %>
              : <%= link_to "#{r.type_renc}", edit_rencontre_path(r), "data-no-turbolink" => true %>
              du <%= link_to "#{r.date.strftime("%d/%m/%y")}", edit_rencontre_path(r), "data-no-turbolink" => true %>
              <% if r.signale %>
                <%= " [#{r.signalement}]" %>
              <% end %>
              <% if r.accomp %>
                <%= " [#{r.type_accomp}]" %>
              <% end %>
              <% if r.details.present? %>
                <br>
                <pre><%= r.details %></pre>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="container" id="container-villes">
    <ul class="villes">
      <% @villes.each do |ville| %>
        <li><%= link_to "#{ville.first}", choix_ville_path(:ville => ville.first) %></li>
      <% end %>
    </ul>
  </div>
</div>


<% if @usagers %>
<hr>
<div id="pqi-print">
  <h3 id="ville-actuelle">
    <%= "#{@ville_actuelle}" %>
    <span class="label label-default"><%= Usager.where(pqi: true, ville: @ville_actuelle).count %></span>
    <%= link_to image_tag("print.png", alt: "Imprimer", width: 30, length: 30), '#', onclick: "printpage()", id: 'print-link', class: "btn" %>
  </h3>

  <table class="usagers table table-responsive table-striped">
    <tr class="table_head">
      <th class="identité">Identité</th>
      <th class="adresse">Adresse</th>
      <th class="rencontres">Dernières rencontres</th>
      <th class="notes">Observations</th>
    </tr>
    <% @usagers.each do |usager| %>
      <tr id="table-pqi">
        <td class="identité-tot">
          <%= link_to "#{usager.sexe} #{usager.nom} #{usager.prenom}", usager %>
          <% if usager.enfants.any? %>
            <br><%= pluralize(usager.enfants.count, 'enfant') %>
          <% end %>
          <% if usager.date_naissance? %>
            <br><%= "#{usager.date_naissance.strftime("%d/%m/%y")}" %>
          <% end %>
          <% if usager.tel? %>
            <br><%= "#{usager.tel}" %>
          <% end %>
          <% if usager.ref.present? %>
            <br><small>Référent : <%= usager.ref %></small>
          <% end %>
          <% if usager.groupe %>
            <br><%= link_to "#{usager.groupe.nom}", usager.groupe %>
          <% end %>
        </td>
        <td class="adresse-tot">
          <%= "#{usager.adresse}" %><br>
          <%= "#{usager.adresse_précis}" %>
        </td>
        <td class="rencontres">
          <% dates_renc = [] %>
          <% Rencontre.where(usager_id: usager.id, prev: false, dnv: false, tel: false).each do |r| %>
            <% dates_renc << "#{r.date.strftime("%d/%m/%y")}" %>
          <% end %>
          <%= dates_5(dates_renc.join(' - ')) %><br>
          <% if Rencontre.find_by(usager_id: usager.id, prev: true) %>
            <% n = Rencontre.where(usager_id: usager.id, prev: true).count %>
            <%= pluralize(n, "rencontre") %> <%= "prévue".pluralize(n) %><br>
          <% end %>
          <%= link_to "Ajouter une rencontre", id_rencontre_path(:id => usager.id), id: 'ajout-rencontre', "data-no-turbolink" => true %>
        </td>
        <td><%= "#{usager.notes}" %></td>
      </tr>
    <% end %>
  <% end %>
  </table>
</div>