config/routes.rb
Rails.application.routes.draw do
  root                    'sessions#new'
  get 'guide'         =>  'static#guide'
  get 'listes'        =>  'static#listes'
  post 'listes'       =>  'static#listes_create'
  get 'signup'        =>  'users#new'
  post 'login' 		    =>  'sessions#create'
  delete 'logout'     =>  'sessions#destroy'
  resources :users
  post 'add'		      =>	'usagers#create'
  get 'pqi'			      =>	'usagers#pqi'
  post 'usagers_vus'  =>  'usagers#post_vus'
  resources :usagers
  get 'stats'         =>  'stats#show'
  post 'stats'        =>  'stats#create'
  resources :maraudes, only: [:index, :show, :destroy, :new, :create]
  resources :rencontres, only: [:edit, :update, :destroy]
  resources :groupes
  resources :structures

  get	'pqi/:ville',
  	:controller => 'usagers',
  	:action 	  => 'pqi',
		:as 		    => :choix_ville

  get 'rencontres/:id',
    :controller => 'rencontres',
    :action     => 'new',
    :as         => :id_rencontre

  post 'rencontres/:id',
    :controller => 'rencontres',
    :action     => 'create',
    :as         => :id_rencontre_create

  get 'rencontres/edit/:id',
    :controller => 'rencontres',
    :action     => 'edit_form',
    :as         => :id_rencontre_edit

  post 'rencontres/edit/:id',
    :controller => 'rencontres',
    :action     => 'post_form',
    :as         => :id_rencontre_post

  get 'rencontres/groupe/:id',
    :controller => 'rencontres',
    :action     => 'new_groupe',
    :as         => :id_groupe

  post 'rencontres/groupe/:id',
    :controller => 'rencontres',
    :action     => 'post_groupe',
    :as         => :id_post_groupe

  get 'maraude-villes/:id',
    :controller => 'maraudes',
    :action     => 'villes',
    :as         => :id_m_villes

  post 'maraude-villes/:id',
    :controller => 'maraudes',
    :action     => 'post_villes',
    :as         => :id_post_villes

  get 'fiche/:id',
    :controller => 'usagers',
    :action     => 'fiche',
    :as         => :id_fiche

  get 'fiche_jour/:id',
    :controller => 'usagers',
    :action     => 'fiche_jour',
    :as         => :id_fiche_jour

  get 'edit_comp/:id',
    :controller => 'usagers',
    :action     => 'edit_comp',
    :as         => :id_edit_comp

  post 'edit_comp/:id',
    :controller => 'usagers',
    :action     => 'post_comp',
    :as         => :id_post_comp

  get 'stats/:date_deb/:date_fin',
    :controller => 'stats',
    :action     => 'show',
    :as         => :stats_dates

  get 'stats/:date_deb/:date_fin/ville/:ville',
    :controller => 'stats',
    :action     => 'show',
    :as         => :stats_dates_ville

  get 'stats/:date_deb/:date_fin/type/:type',
    :controller => 'stats',
    :action     => 'show',
    :as         => :stats_dates_type

  get 'stats/:date_deb/:date_fin/:type/:ville',
    :controller => 'stats',
    :action     => 'show',
    :as         => :stats_dates_type_ville

  get 'listes/:choix',
    :controller => 'static',
    :action     => 'listes',
    :as         => :listes_choix

  delete 'listes/Intervenants/:id',
    :controller => 'static',
    :action     => 'interv_destroy',
    :as         => :interv_destroy

  post 'listes/Intervenants',
    :controller => 'static',
    :action     => 'interv_create',
    :as         => :interv_create

  delete 'listes/Villes/:id',
    :controller => 'static',
    :action     => 'ville_destroy',
    :as         => :ville_destroy

  post 'listes/Villes',
    :controller => 'static',
    :action     => 'ville_create',
    :as         => :ville_create

  delete 'listes/Types/:id',
    :controller => 'static',
    :action     => 'type_destroy',
    :as         => :type_destroy

  post 'listes/Types',
    :controller => 'static',
    :action     => 'type_create',
    :as         => :type_create
end

app/models/rencontre.rb
class Rencontre < ActiveRecord::Base
  belongs_to :usager

  default_scope -> { order(date: :desc) }

  validates :usager_id, presence: true,
  						uniqueness: { scope: [:date, :type_renc] }
  validates :date, presence: true
  validates :type_renc, presence: true
  validates :ville, presence: true

  	def self.search(search)
      if search
        if Rails.env.production?
          joins(:usager).where("to_char(rencontres.date, 'DD/MM/YYYY') ILIKE? OR rencontres.type_renc ILIKE? OR usagers.nom ILIKE? OR usagers.prenom ILIKE? OR usagers.sexe ILIKE?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
        else
          joins(:usager).where("rencontres.date LIKE? OR rencontres.type_renc LIKE? OR usagers.nom LIKE? OR usagers.prenom LIKE? OR usagers.sexe LIKE?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
        end
      else
        scoped
      end
    end
end

app/controllers/rencontres_controller.rb
class RencontresController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :new_groupe, :post_groupe, :edit_form, :post_form, :destroy, :edit, :update]

  def new
    store_id
    @signalements = [ ["Signalement 115", "Signalement 115"],
                      ["Signalement tiers", "Signalement tiers"],
                      ["Croisé(e) en maraude", "Croisé(e) en maraude"]]
    @types = []
    TypeRenc.all.each do |t|
      @types << ["#{t.nom}"]
    end
    @prestas = [["Prestation alimentaire", "Prestation alimentaire"],
                ["Vestiaire", "Vestiaire"],
                ["Duvet", "Duvet"],
                ["Hygiène", "Hygiène"]]
    @accomps = [["Accompagnement 115", "Accompagnement 115"],
                ["Accompagnement SIAO", "Accompagnement SIAO"],
                ["Autre", "Autre"]]
    @villes = []
    Ville.where(ville_93: true).order('nom ASC').each do |v|
      @villes << ["#{v.nom}"]
    end
    @usager = Usager.find(session[:stored_id])
    @nb_enf = []
    i = 0
    until i == @usager.enfants.count + 1 do
      @nb_enf << ["#{i}", "#{i}"]
      i += 1
    end
    gon.renc = []
    if @usager.rencontres.any?
      @usager.rencontres.each do |r|
        gon.renc << "#{r.date.strftime('%d/%m/%Y')}"
      end
    end
    @rencontre = @usager.rencontres.build
    session.delete(:stored_id)
  end

  def create
    store_id
    @usager = Usager.find(session[:stored_id])
    @rencontre = @usager.rencontres.build(rencontre_params)
    @rencontre.user_id = current_user.id
    if current_user.benev?
      @rencontre.prev = false
    end
    if session.has_key?('groupe')
      @rencontre.date = session[:date]
      @rencontre.type_renc = session[:type_renc]
      @rencontre.ville = session[:ville]
    else
      @rencontre.date = params[:rencontre][:date].to_date.strftime("%F")
    end
    if @rencontre.valid?
      if TypeRenc.find_by(nom: @rencontre.type_renc).mar? && !@rencontre.prev
        mar = true
        if !Maraude.find_by(date: @rencontre.date, type_maraude: @rencontre.type_renc).present?
          @maraude = Maraude.create(date: @rencontre.date, type_maraude: @rencontre.type_renc, villes: "")
        end
      else
        mar = false
        if @rencontre.dnv
          err = true
          flash[:danger] = "Erreur : Maraude déplacée mais personne non vue alors qu'il ne s'agit pas d'une maraude ou que la rencontre est prévisionnelle"
        end
      end
      rencontre_u = "// #{@rencontre.type_renc} [#{@rencontre.date.strftime("%d/%m/%y")}] //"
      if @rencontre.signale && !@rencontre.signalement.empty?
        rencontre_u << "\n#{@rencontre.signalement}"
        if @rencontre.signalement == "Signalement tiers" && @rencontre.sig_contact.present?
          rencontre_u << " (Contact : #{@rencontre.sig_contact}"
          rencontre_u << " / Coordonnées : #{@rencontre.sig_coords}" unless @rencontre.sig_coords.empty?
          rencontre_u << ")"
        end
      end
      if @rencontre.accomp && !@rencontre.type_accomp.empty?
        rencontre_u << "\n#{@rencontre.type_accomp}"
      end
      rencontre_p = params[:rencontre][:prestas].reject{ |a| a == '0' }.join(' #')
      if rencontre_p && !rencontre_p.empty?
        rencontre_u << "\n#{rencontre_p.split(' #').join(' - ')}"
      end
      if @rencontre.dnv
        rencontre_u << "\nMaraude déplacée mais personne non vue."
      end
      if @rencontre.tel
        rencontre_u << "\nJoint au téléphone."
      end
      if @usager.enfants.any? && !@rencontre.dnv
        rencontre_u << "\nAvec #{@rencontre.nb_enf} #{"enfant".pluralize(@rencontre.nb_enf)}."
      end
      if !@rencontre.details.empty?
        rencontre_u << "\n#{@rencontre.details}"
      else
        rencontre_u << "\nRencontre sans détails."
      end
      rencontre_u << "\n\n\n" unless !@usager.fiche
      rencontre_u << "#{@usager.fiche}"
      u_fiche = rencontre_u
      if @rencontre.signale
        if !@rencontre.signalement.empty?
          if @rencontre.signalement == "Signalement tiers" && @rencontre.sig_structure.present?
            struc = Structure.find_or_create_by(nom: @rencontre.sig_structure.split(' ').map(&:capitalize).join(' ').split('-').map(&:capitalize).join('-'))
          end
          if !mar && !@rencontre.prev
            errb = true
            if err
              flash[:danger] << " et signalement alors que la rencontre annoncée n'est pas une maraude"
            else
              flash[:danger] = "Erreur : signalement alors que la rencontre annoncée n'est pas une maraude"
            end
          end
        else
          errb = true
          if err
            flash[:danger] << "et précisez le type de signalement"
          else
            flash[:danger] = "Précisez le type de signalement"
          end
        end
      else
        params[:rencontre][:signalement] = nil
      end
      if @rencontre.accomp
        if !@rencontre.type_accomp.empty?
          if @rencontre.accomp_structure.present?
            struc = Structure.find_or_create_by(nom: @rencontre.accomp_structure.split(' ').map(&:capitalize).join(' ').split('-').map(&:capitalize).join('-'))
          end
          if @rencontre.dnv
            errc = true
            if err || errb
              flash[:danger] << " et accompagnement alors que la maraude s'est déplacée sans voir la personne"
            else
              flash[:danger] = "Erreur : accompagnement alors que la maraude s'est déplacée sans voir la personne"
            end
          end
        else
          errc = true
          if err || errb
            flash[:danger] << " et précisez le type d'accompagnement"
          else
            flash[:danger] = "Précisez le type d'accompagnement"
          end
        end
      else
        params[:rencontre][:type_accomp] = nil
      end
      if !err && !errb && !errc
        @usager.fiche = u_fiche if u_fiche
        @usager.save
        @rencontre.nb_enf = nil unless @rencontre.nb_enf
        @rencontre.prestas = rencontre_p
        if session.has_key?('usagers_ids')
          session[:groupe] = true
          if session[:usagers_ids] == []
            session.delete(:usagers_ids)
          end
        else
          session.delete(:date)
          session.delete(:type_renc)
          session.delete(:ville)
        end
        @rencontre.save
        flash[:success] = "Rencontre ajoutée avec #{@usager.sexe} #{@usager.nom} #{@usager.prenom}"
        if !session[:usagers_ids]
          if @usager.groupe && @usager.groupe.usagers.count > 1 && !session[:groupe]
            session[:type_renc] = @rencontre.type_renc
            session[:date] = @rencontre.date
            session[:ville] = @rencontre.ville
            redirect_to id_groupe_path(:id => @usager.id)
          else
            redirect_to @usager
          end
          if session[:groupe]
            session.delete(:groupe)
          end
        else
          redirect_to id_rencontre_path(:id => session[:usagers_ids].pop)
        end
      else
        redirect_to id_rencontre_path(:id => @usager.id)
      end
    elsif Rencontre.where(usager_id: @usager.id, date: params[:rencontre][:date], type_renc: params[:rencontre][:type_renc])
      flash[:danger] = "Cette rencontre existe déjà ou il manque des informations nécessaires"
      redirect_to id_rencontre_path(:id => @usager.id)
    elsif params[:rencontre][:date].blank?
      flash[:danger] = "Renseignez une date"
      redirect_to id_rencontre_path(:id => @usager.id)
    elsif params[:rencontre][:type_renc].empty?
      flash[:danger] = "Précisez un type de rencontre"
      redirect_to id_rencontre_path(:id => @usager.id)
    elsif params[:rencontre][:ville].empty?
      flash[:danger] = "Précisez une ville de rencontre"
      redirect_to id_rencontre_path(:id => @usager.id)
    end
    session.delete(:stored_id)
  end

  def new_groupe
    store_id
    @usager = Usager.find(session[:stored_id])
    @groupe = @usager.groupe
    @usagers = @groupe.usagers.select{ |usager| usager.id != @usager.id }
    session.delete(:stored_id)
  end

  def post_groupe
    store_id
    u = Usager.find(session[:stored_id])
    session[:usagers_ids] = params[:rencontre][:usagers].reject{ |a| a == '0' }
    session[:groupe] = true
    if session[:usagers_ids].empty?
      redirect_to u
    else
      redirect_to id_rencontre_path(:id => session[:usagers_ids].pop)
    end
    session.delete(:stored_id)
  end

  def destroy
    r = Rencontre.find(params[:id])
    @usager = Usager.find(r.usager_id)
    if current_user.benev? && r.type_renc != "Maraude bénévoles"
      flash[:danger] = "Accès restreint"
      redirect_to id_rencontre_edit_path(id: @usager.id)
    else
      if @usager.fiche.present?
        u_del = @usager.fiche.split("//")
        rank = u_del.index(" #{r.type_renc} [#{r.date.strftime("%d/%m/%y")}] ")
        if rank
          while rank != nil
            u_del = u_del[0..(rank-1)].concat(u_del[(rank+2)..(u_del.length-1)])
            rank = u_del.index(" #{r.type_renc} [#{r.date.strftime("%d/%m/%y")}] ")
          end
        end
        @usager.fiche = "#{u_del.join("//")}"
        @usager.save
      end
      r.destroy
      flash[:success] = "Rencontre supprimée (Vérifiez que la rencontre a bien été retirée dans la fiche suivi de l'usager)"
      redirect_to @usager
    end
  end

  def edit_form
    delete_groupe
    store_id
    @types = []
    TypeRenc.all.each do |t|
      @types << ["#{t.nom}"]
    end
    @usager = Usager.find_by(id: session[:stored_id])
    session.delete(:stored_id)
  end

  def post_form
    store_id
    @usager = Usager.find(session[:stored_id])
    r = Rencontre.find_by(usager_id: @usager.id,
                          date: params[:rencontres][:date].to_date.strftime("%F"),
                          type_renc: params[:rencontres][:type_renc])
    if current_user.benev? && r.type_renc != "Maraude bénévoles"
      flash[:danger] = "Accès restreint"

app/helpers/rencontres_helper.rb
module RencontresHelper
end

app/views/rencontres/_form.html.erb
<%= form_for(@rencontre, url: id_rencontre_create_path(id: @usager.id), method: :post) do |f| %>

<h1>
  Ajouter une rencontre avec <%= "#{@usager.sexe} #{@usager.nom} #{@usager.prenom}" %>
  <% if current_user.benev? %>
    <br><small>Maraude bénévoles</small>
  <% end %>
</h1>


<% unless session[:groupe] %>
  <div class="form-horizontal">
    <div class="part part-hover necessary">
      <h3>Informations nécessaires</h3>

      <div class="form-group">
        <%= f.label :date, class: "control-label col-md-3 col-sm-3 col-xs-3" %>
        <div class="col-md-9 col-sm-9 col-xs-9 input-group date" id="datepicker">
          <%= f.text_field :date, class: 'form-control', data: { date_format: 'DD/MM/YYYY', locale: 'fr' }, value: Date.today.strftime("%d/%m/%Y") %>
          <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :type_renc, "Type", class: "control-label col-md-3 col-sm-3 col-xs-3" %>
        <div class="col-md-9 col-sm-9 col-xs-9">
          <% unless current_user.benev? %>
            <%= f.select :type_renc, @types, prompt: "Quel type de rencontre ?", class: 'form-control' %>
          <% else %>
            <%= f.select :type_renc, ["Maraude bénévoles", "Maraude bénévoles"], disabled: true, class: 'form-control' %>
          <% end %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :ville, class: "control-label col-md-3 col-sm-3 col-xs-3" %>
        <div class="col-md-9 col-sm-9 col-xs-9">
          <%= f.select :ville, @villes, class: 'form-control', selected: @usager.ville %>
        </div>
      </div>
    </div>
  </div>

  <hr>
<% end %>

<div class="part part-hover">
  <h3>Signalement</h3>

  <div class="row">
    <div class="col-md-6 col-sm-6 col-xs-6 form-inline">
      <%= f.label :signale, "Nouveau signalement" %>
      <%= f.check_box :signale, class: 'form-control check sig' %>
    </div>

    <div class="col-md-6 col-sm-6 col-xs-6 appear form-inline">
      <%= f.label :signalement, "Type" %>
      <%= f.select :signalement,  [ ["Signalement 115", "Signalement 115"],
                                    ["Signalement tiers", "Signalement tiers"]],
                                    prompt: "Quel type de signalement ?",
                                    class: 'form-control' %>
    </div>
  </div>

  <div class="appear" style="margin-top:20px">
    <div class="form-horizontal">
      <div class="form-group">
        <%= f.label :sig_structure, "Structure (le cas échéant)", class: "control-label col-md-3 col-sm-3 col-xs-3" %>
        <div class="col-md-9 col-sm-9 col-xs-9">
          <%= f.text_field :sig_structure, data: {autocomplete_source: Structure.order(:nom).map(&:nom)}, class: 'form-control five-lv' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :sig_contact, "Contact", class: "control-label col-md-3 col-sm-3 col-xs-3" %>
        <div class="col-md-9 col-sm-9 col-xs-9">
          <%= f.text_field :sig_contact, class: 'form-control five-lv' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :sig_coords, "Coordonnées", class: "control-label col-md-3 col-sm-3 col-xs-3" %>
        <div class="col-md-9 col-sm-9 col-xs-9">
          <%= f.text_area :sig_coords, class: 'form-control five-lv', rows: 2 %>
        </div>
      </div>
    </div>
  </div>
</div>

<hr>

<div class="part part-hover">
  <h3>Accompagnement</h3>

  <div class="row form-inline">
    <div class="col-md-6 col-sm-6 col-xs-6">
      <%= f.label :accomp, "Accompagnement" %>
      <%= f.check_box :accomp, checked: false, class: 'form-control check sig' %>
    </div>

    <div class="col-md-6 col-sm-6 col-xs-6 appear">
      <%= f.label :type_accomp, "Type" %>
      <%= f.select :type_accomp, @accomps, prompt: "Quel type d'accompagnement ?", class: 'form-control' %>
    </div>
  </div>

  <div class="appear" style="margin-top:20px">
    <div class="form-horizontal">
      <div class="form-group">
        <%= f.label :accomp_structure, "Structure", class: "control-label col-md-3 col-sm-3 col-xs-3" %>
        <div class="col-md-9 col-sm-9 col-xs-9">
          <%= f.text_field :accomp_structure, data: {autocomplete_source: Structure.order(:nom).map(&:nom)}, class: 'form-control five-lv' %>
        </div>
      </div>
    </div>
  </div>
</div>

<hr>

<div class="part part-hover">
  <h3>Options</h3>

  <div class="form-inline">
    <%= f.label :dnv, "Maraude déplacée mais personne non vue" %>
    <%= f.check_box :dnv, checked: false, class: 'form-control two-lv' %>
  </div>

  <div class="form-inline">
    <%= f.label :tel, "Joint au téléphone (cocher seulement si usager non vu)" %>
    <%= f.check_box :tel, checked: false, class: 'form-control two-lv' %>
  </div>

  <% unless current_user.benev? %>
    <div class="form-inline">
      <%= f.label :prev, "Rencontre prévisionnelle" %>
      <%= f.check_box :prev, checked: false, class: 'form-control two-lv' %>
    </div>
  <% end %>
</div>

<hr>

<div class="part part-hover">
  <h3>Détails</h3>
  <div class="form-group">
    <%= f.text_area :details, class: 'form-control two-lv', html: {style: 'text-align:center'}, rows: 10 %>
  </div>

  <% if @usager.enfants.any? %>
    <div class="form-group">
      <%= f.label :nb_enf, "Nombre d'enfants vus" %>
      <%= f.select :nb_enf, @nb_enf, class: 'form-control two-lv' %>
    </div>
  <% end %>
</div>

<hr>

<div class="part part-hover">
  <h3>Prestations</h3>

  <div>
    <% for presta in @prestas do %>
      <%= f.check_box :prestas, { :multiple => true }, "#{presta.first}" %>
      <%= presta.first %><br>
    <% end %>
  </div>
</div>

<hr>

<div class="text-center">
  <div class="btn-group">
    <%= f.submit "Valider la rencontre", class: 'btn btn-primary', id: 'submit' %>

    <% if Usager.maximum("id") == @usager.id %>
      <%= link_to "Pas besoin", @usager, class: "btn btn-danger" %>
    <% end %>
  </div>
</div>

<% end %>

app/views/rencontres/edit.html.erb
<script>
var val_stock = ""
var val = ""

$(document).ready(function(){
    $("#submit").mouseenter(function(){
        val = $("#rencontre_date").val();
        if (val_stock != val) {
            val_stock = val;
            if (gon.renc.indexOf(val) > -1) {
                alert("Etes-vous sûr(e) ? Cette personne a déjà été rencontrée le " + val + ". S'il s'agit d'une simple édition de rencontre dont on n'a pas changé la date, ne pas prendre ce message en compte.");
            };
        };
    });
});
</script>

<% provide(:title, "#{@rencontre.type_renc}") %>

<div class="row">
  <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-8 col-xs-offset-2">
    <%= render 'form_for_edit' %>
  </div>
</div>

app/views/rencontres/edit_form.html.erb
<% provide(:title, "Editer ou supprimer une rencontre") %>

<h1>Editer ou supprimer une rencontre avec <%= @usager.sexe %> <%= @usager.nom %> <% @usager.prenom %></h1>

<%= simple_form_for(:rencontres, url: id_rencontre_post_path(id: @usager.id), html: { class: "form-inline text-center" }) do |f| %>

	<div>
		<h3>Date</h3>

	  <div class="input-group date" id="datepicker">
      <%= f.text_field :date, class: 'form-control', data: { date_format: 'DD/MM/YYYY', locale: 'fr' }, value: Date.today.strftime("%d/%m/%Y") %>
      <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
    </div>
	</div>

	<div>
		<h3>Type</h3>

	  <%= f.select :type_renc, @types, prompt: "Quel type de rencontre ?", class: 'form-control' %><br>
	</div>

	<hr>

	<div class="btn-group">
		<%= f.submit "Editer", 	class: 'btn btn-info',
	  												id: 'submit',
	  												name: "edit_renc" %>

	  <%= f.submit "Supprimer", class: 'btn btn-danger',
	  													id: 'submit',
	  													name: "suppr_renc",
	  													data: { confirm: "Etes-vous sûr(e) ?"} %>
	</div>
<% end %>

app/views/rencontres/new.html.erb
<script>
var val_stock = ""
var val = ""

$(document).ready(function(){
    $("#submit").mouseenter(function(){
        val = $("#rencontre_date").val();
        if (val_stock != val) {
            val_stock = val;
            if (gon.renc.indexOf(val) > -1) {
                alert("Etes-vous sûr(e) ? Cette personne a déjà été rencontrée le " + val + ".");
            };
        };
    });
});
</script>

<% provide(:title, "Rencontre avec #{@usager.sexe} #{@usager.nom} #{@usager.prenom}") %>

<div class="row">
  <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-8 col-xs-offset-2">
    <%= render 'form' %>
  </div>
</div>

app/views/rencontres/new_groupe.html.erb
<% provide(:title, 'Rencontre de groupe') %>

<h3>Rencontre avec d'autres usagers du groupe "<%= @groupe.nom %>" sur la même intervention ?</h3>

<%= form_for(:rencontre, url: id_post_groupe_path(id: @usager.id), method: "POST") do |f| %>

  <% for usager in @usagers do %>
    <%= f.check_box :usagers, { :multiple => true, :checked => false }, usager.id %>
    <%= "#{usager.sexe} #{usager.nom} #{usager.prenom}" %><br>
  <% end %>

  <div class="text-center" style="margin-top: 30px">
  	<%= f.submit "Valider", class: "btn btn-primary" %>
  </div>
<% end %>