config/routes.rb
Rails.application.routes.draw do
  root                    'sessions#new'
  get 'guide'         =>  'static#guide'
  get 'listes'        =>  'static#listes'
  post 'listes'       =>  'static#listes_create'
  get 'signup'        =>  'users#new'
  post 'login' 		    =>  'sessions#create'
  delete 'logout'     =>  'sessions#destroy'
  resources :users
  post 'add'		      =>	'usagers#create'
  get 'pqi'			      =>	'usagers#pqi'
  post 'usagers_vus'  =>  'usagers#post_vus'
  resources :usagers
  get 'stats'         =>  'stats#show'
  post 'stats'        =>  'stats#create'
  resources :maraudes, only: [:index, :show, :destroy, :new, :create]
  resources :rencontres, only: [:edit, :update, :destroy]
  resources :groupes
  resources :structures

  get	'pqi/:ville',
  	:controller => 'usagers',
  	:action 	  => 'pqi',
		:as 		    => :choix_ville

  get 'rencontres/:id',
    :controller => 'rencontres',
    :action     => 'new',
    :as         => :id_rencontre

  post 'rencontres/:id',
    :controller => 'rencontres',
    :action     => 'create',
    :as         => :id_rencontre_create

  get 'rencontres/edit/:id',
    :controller => 'rencontres',
    :action     => 'edit_form',
    :as         => :id_rencontre_edit

  post 'rencontres/edit/:id',
    :controller => 'rencontres',
    :action     => 'post_form',
    :as         => :id_rencontre_post

  get 'rencontres/groupe/:id',
    :controller => 'rencontres',
    :action     => 'new_groupe',
    :as         => :id_groupe

  post 'rencontres/groupe/:id',
    :controller => 'rencontres',
    :action     => 'post_groupe',
    :as         => :id_post_groupe

  get 'maraude-villes/:id',
    :controller => 'maraudes',
    :action     => 'villes',
    :as         => :id_m_villes

  post 'maraude-villes/:id',
    :controller => 'maraudes',
    :action     => 'post_villes',
    :as         => :id_post_villes

  get 'fiche/:id',
    :controller => 'usagers',
    :action     => 'fiche',
    :as         => :id_fiche

  get 'fiche_jour/:id',
    :controller => 'usagers',
    :action     => 'fiche_jour',
    :as         => :id_fiche_jour

  get 'edit_comp/:id',
    :controller => 'usagers',
    :action     => 'edit_comp',
    :as         => :id_edit_comp

  post 'edit_comp/:id',
    :controller => 'usagers',
    :action     => 'post_comp',
    :as         => :id_post_comp

  get 'stats/:date_deb/:date_fin',
    :controller => 'stats',
    :action     => 'show',
    :as         => :stats_dates

  get 'stats/:date_deb/:date_fin/ville/:ville',
    :controller => 'stats',
    :action     => 'show',
    :as         => :stats_dates_ville

  get 'stats/:date_deb/:date_fin/type/:type',
    :controller => 'stats',
    :action     => 'show',
    :as         => :stats_dates_type

  get 'stats/:date_deb/:date_fin/:type/:ville',
    :controller => 'stats',
    :action     => 'show',
    :as         => :stats_dates_type_ville

  get 'listes/:choix',
    :controller => 'static',
    :action     => 'listes',
    :as         => :listes_choix

  delete 'listes/Intervenants/:id',
    :controller => 'static',
    :action     => 'interv_destroy',
    :as         => :interv_destroy

  post 'listes/Intervenants',
    :controller => 'static',
    :action     => 'interv_create',
    :as         => :interv_create

  delete 'listes/Villes/:id',
    :controller => 'static',
    :action     => 'ville_destroy',
    :as         => :ville_destroy

  post 'listes/Villes',
    :controller => 'static',
    :action     => 'ville_create',
    :as         => :ville_create

  delete 'listes/Types/:id',
    :controller => 'static',
    :action     => 'type_destroy',
    :as         => :type_destroy

  post 'listes/Types',
    :controller => 'static',
    :action     => 'type_create',
    :as         => :type_create
end

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right navbot">
        <% if logged_in? %>
          <li id="left-li"><%= link_to "#{current_user.identifiant}", current_user %></li>
          <li><%= link_to "Editer profil", edit_user_path(current_user) %></li>
          <li><%= link_to "Utilisateurs", users_path %></li>
          <li><%= link_to "Guide d'utilisation", guide_path %></li>
          <% if current_user.admin? %>
            <li><%= link_to "Listes", listes_path %></li>
          <% end %>
          <li><%= link_to "Déconnexion", logout_path, method: "delete" %></li>
          <li class="navbot-icon">
            <%= link_to '☰', "javascript:void(0);", id: "navbot-icon" %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right navtop">
        <li><%= link_to "Accueil",   root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Ajouter usager", new_usager_path, "data-no-turbolink" => true %></li>
          <li><%= link_to "PQI", pqi_path %></li>
          <li><%= link_to "Maraudes", maraudes_path %></li>
          <li><%= link_to "Structures", structures_path %></li>
          <li><%= link_to "Statistiques", stats_path unless current_user.benev? %></li>
          <li class="navtop-icon">
            <%= link_to '☰', "javascript:void(0);", id: "navtop-icon" %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= include_gon(:init => true) %>
  <%= Gon::Base.render_data({}) %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <script type="text/javascript">$.widget.bridge('uitooltip', $.ui.tooltip);</script>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
  	<%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>